spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/investor_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=?Gore#!OT?!YMA

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
google.client.id=252544602687-r6q4n8fsmg4vlj3djke65tjgmh5mnbkc.apps.googleusercontent.com
